[package]
name = "goble-ui"
version = "0.1.0"
edition = "2021"
authors.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
goble-core = { path = "../goble-core" }
wgpu.workspace = true
winit.workspace = true
glam.workspace = true
bytemuck.workspace = true
pollster.workspace = true
image.workspace = true
anyhow.workspace = true
thiserror.workspace = true

[dev-dependencies]

[lints]
workspace = true
