apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goblin-cluster.fullname" . }}-bundle
  labels:
    {{- include "goblin-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  worker-bundle.json: {{ required "workerBundle is required" .Values.workerBundle }}
---
{{- if .Values.clusterKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goblin-cluster.fullname" . }}-cluster-key
  labels:
    {{- include "goblin-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  cluster-key: {{ .Values.clusterKey | b64enc }}
{{- end }}
---
{{- if .Values.snapshot.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "goblin-cluster.fullname" . }}-snapshot
  labels:
    {{- include "goblin-cluster.labels" . | nindent 4 }}
type: Opaque
data:
  provider: {{ .Values.snapshot.provider | b64enc }}
  endpoint: {{ .Values.snapshot.endpoint | b64enc }}
  bucket: {{ .Values.snapshot.bucket | b64enc }}
  prefix: {{ .Values.snapshot.prefix | b64enc }}
  access-key-id: {{ .Values.snapshot.accessKeyId | b64enc }}
  secret-access-key: {{ .Values.snapshot.secretAccessKey | b64enc }}
  region: {{ .Values.snapshot.region | b64enc }}
  interval-seconds: {{ .Values.snapshot.intervalSeconds | toString | b64enc }}
{{- end }}
